services:
  - type: web
    name: pdf-toolkit
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app_simple.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: PORT
        value: 10000